# Generated by Django 2.2.4 on 2022-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desctipiton',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
