# Generated by Django 2.2.4 on 2022-10-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksapp', '0002_book_desctipiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desctipiton',
            new_name='description',
        ),
    ]
